/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.cpq.service;
import cn.zhuatech.cpq.common.BusinessException; import cn.zhuatech.cpq.dto.CpqDto.*; import cn.zhuatech.cpq.model.*; import cn.zhuatech.cpq.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class CpqService {
    private final QuoteRepository orders; private final QuoteRevisionRepository reports; private final PriceRuleRepository priceRule; private final ApprovalRequestRepository approvalRequests; private final CurrentUserService current;
    public CpqService(QuoteRepository orders,QuoteRevisionRepository reports,PriceRuleRepository priceRule,ApprovalRequestRepository approvalRequests,CurrentUserService current){this.orders=orders;this.reports=reports;this.priceRule=priceRule;this.approvalRequests=approvalRequests;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getCatalogCode();List<Quote> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByCatalogCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<QuoteView> quotes(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){Quote order=orders.findById(id).orElseThrow(()->new BusinessException("报价任务不存在"));if(order.getStatus()==Quote.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new QuoteRevision(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<Quote> list){int planned=list.stream().mapToInt(Quote::getPlannedQty).sum(),done=list.stream().mapToInt(Quote::getCompletedQty).sum(),defects=list.stream().mapToInt(Quote::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日报价",String.format("%,d",planned),list.size()+" 张报价任务","blue"),new Metric("报价完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("价格规则异常",priceRule.countByStatus(PriceRule.Status.ALARM)+"",approvalRequests.countByResult(ApprovalRequest.Result.PENDING)+" 项待审批","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),priceRule.findAllByOrderByCodeAsc().stream().map(e->new PriceRuleView(e.getCode(),e.getName(),e.getCatalog().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),approvalRequests.findTop10ByOrderByIdDesc().stream().map(i->new ApprovalRequestView(i.getApprovalRequestNo(),i.getQuote().getOrderNo(),i.getQuote().getProductName(),i.getApprovalRequestType(),i.getApprovalRequestQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private QuoteView view(Quote o){return new QuoteView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getCatalog().getName(),o.getCatalog().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(Quote o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
